import type { ExpertSummary } from "@/lib/api/types";

// Static placeholder data for the pre-auth dashboard shell (phases 1-3 of
// DASHBOARD_PLAN.md). Shaped exactly like GET /experts so swapping in
// react-query + the real endpoint later is a drop-in replacement.
export const MOCK_EXPERTS: ExpertSummary[] = [
  {
    id: 1,
    name: "stoic-philosophy",
    topic: "Stoic philosophy",
    status: "ready",
    tier: "pro",
    persona_name: "Marcus",
    persona_bio: "A calm, first-principles guide to Stoic ethics and practice.",
    persona_style: "measured, direct",
    avg_quality: 0.94,
    key_concepts: ["dichotomy of control", "virtue ethics", "amor fati"],
    source_count: 42,
    chunk_count: 1180,
    node_count: 640,
    edge_count: 1502,
    source_type_counts: { wikipedia: 12, pdf: 18, url: 12 },
    created_at: "2026-06-28T14:02:00Z",
  },
  {
    id: 2,
    name: "propertygraph-rag",
    topic: "Property graph RAG architectures",
    status: "building",
    tier: "standard",
    persona_name: null,
    persona_bio: null,
    persona_style: null,
    avg_quality: null,
    key_concepts: [],
    source_count: 18,
    chunk_count: 340,
    node_count: 0,
    edge_count: 0,
    source_type_counts: { arxiv: 9, url: 9 },
    created_at: "2026-07-04T09:15:00Z",
  },
  {
    id: 3,
    name: "roman-law",
    topic: "Roman law and jurisprudence",
    status: "ready",
    tier: "standard",
    persona_name: "Cicero",
    persona_bio: "An orator's take on Roman legal reasoning and precedent.",
    persona_style: "rhetorical, precise",
    avg_quality: 0.89,
    key_concepts: ["ius civile", "praetorian edict", "twelve tables"],
    source_count: 27,
    chunk_count: 810,
    node_count: 402,
    edge_count: 955,
    source_type_counts: { wikipedia: 14, pdf: 13 },
    created_at: "2026-06-20T11:40:00Z",
  },
  {
    id: 4,
    name: "distributed-consensus",
    topic: "Distributed consensus algorithms",
    status: "failed",
    tier: "lite",
    persona_name: null,
    persona_bio: null,
    persona_style: null,
    avg_quality: null,
    key_concepts: [],
    source_count: 6,
    chunk_count: 40,
    node_count: 0,
    edge_count: 0,
    source_type_counts: { url: 6 },
    created_at: "2026-07-02T18:30:00Z",
  },
  {
    id: 5,
    name: "byzantine-history",
    topic: "Byzantine imperial history",
    status: "ready",
    tier: "lite",
    persona_name: "Anna",
    persona_bio: "A court-historian's narrative style, citation-heavy.",
    persona_style: "narrative, citation-heavy",
    avg_quality: 0.81,
    key_concepts: ["theme system", "iconoclasm", "Komnenian restoration"],
    source_count: 15,
    chunk_count: 460,
    node_count: 210,
    edge_count: 480,
    source_type_counts: { wikipedia: 10, pdf: 5 },
    created_at: "2026-06-15T08:05:00Z",
  },
  {
    id: 6,
    name: "queued-example",
    topic: "Behavioral economics",
    status: "queued",
    tier: "standard",
    persona_name: null,
    persona_bio: null,
    persona_style: null,
    avg_quality: null,
    key_concepts: [],
    source_count: 0,
    chunk_count: 0,
    node_count: 0,
    edge_count: 0,
    source_type_counts: {},
    created_at: "2026-07-04T16:50:00Z",
  },
];

export const MOCK_BUILDS_OVER_TIME = [
  { date: "06-29", builds: 2 },
  { date: "06-30", builds: 1 },
  { date: "07-01", builds: 3 },
  { date: "07-02", builds: 1 },
  { date: "07-03", builds: 4 },
  { date: "07-04", builds: 2 },
];
