'use client'

import { MessageSquare, RotateCcw } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'

import { ASK_FIELD_ID, NewChatComposer } from '@/components/chat/new-chat-composer'
import { OverviewCoverage } from '@/components/experts/overview/coverage'
import { OverviewHeader } from '@/components/experts/overview/header'
import { OverviewProperties } from '@/components/experts/overview/properties'
import { ShareDialog } from '@/components/experts/share-panel'
import { TopBar } from '@/components/shell/top-bar'
import { Button, ButtonLink } from '@/components/ui/button'
import { MenuItem, MenuLinkItem, MenuSeparator } from '@/components/ui/menu'
import { Notice } from '@/components/ui/notice'
import { RelativeTime } from '@/components/ui/relative-time'
import { dotState } from '@/components/ui/status-dot'
import { useLeaveExpert } from '@/hooks/use-leave-expert'
import { canManage } from '@/lib/access'
import { describeBuildFailure } from '@/lib/build/copy'
import { cn } from '@/lib/cn'
import { chatTitle, plural } from '@/lib/format'
import { displayName } from '@/lib/persona'
import type { BuildStatus, ConversationSummary, ExpertWithCatalog } from '@/lib/api/types'

/**
 * The expert's Overview: a document, not a dashboard.
 *
 * Sigil where the reference has its emoji, the persona name as a 24px title,
 * the topic as the description line, then a properties block of inline
 * label · value rows, then prose sections. The properties stack label-over-value
 * below 480px rather than squeezing two columns into 360px.
 *
 * **Asking comes first for a new expert.** With no chats yet, the composer sits
 * directly under the header: the payoff of a build is asking it something, and
 * as the last section of a long document it was the thing people had to go and
 * find. Once there are chats it returns to the foot of the page, beside them.
 *
 * **A failed build shows the failure and nothing that describes a corpus.** A
 * failed expert has no sources to have assembled, so the notice, the properties
 * and the way back are the whole page.
 *
 * **Chat is gated on `readiness`, never on `status`.** An expert whose chunks
 * are embedded answers questions a whole stage before its build job finishes,
 * and reading `status` here would hide a working expert for the length of graph
 * extraction.
 *
 * **A viewer sees the document, not the controls.** Someone reading through a
 * share link gets every section and the composer, and nothing that changes the
 * expert: no avatar picker, no rebuild, no Settings, no Share. Their one action
 * on the expert itself is removing it from their own workspace.
 */
export function OverviewPage({
  expert,
  conversations,
  buildStatus,
}: {
  expert: ExpertWithCatalog
  conversations: ConversationSummary[]
  buildStatus: BuildStatus | null
}) {
  const name = displayName(expert)
  const owner = canManage(expert)
  const [sharing, setSharing] = useState(false)
  const { leave } = useLeaveExpert(expert.name, name)
  const chattable = expert.readiness !== 'pending'
  const state = dotState(expert.status, expert.readiness, expert.build_active)
  const building = state === 'queued' || state === 'building'
  const failed = expert.status === 'failed' && !chattable
  const askFirst = chattable && conversations.length === 0
  // A build that finished but left no persona: the corpus is usable and the
  // voice can be regenerated by rebuilding. Worth saying, not worth hiding.
  //
  // Keyed on `state`, never on `expert.status`. An expert whose row still says
  // `building` with no job behind it displays as Ready — and read from the raw
  // status this notice never fired, so the page showed a topic, no About and a
  // heading reading "Ask Thomism", with nothing anywhere to say why.
  const degradedPersona = state === 'ready' && !expert.persona_name
  // With no persona there is no one to address: "Ask Thomism" reads as a
  // instruction to a subject, not an invitation.
  const askHeading = expert.persona_name ? `Ask ${name}` : 'Ask a question'

  const ask = (
    <section id="ask" className={cn('scroll-mt-16', askFirst ? 'mt-6' : 'mt-10')}>
      <h2 className="text-lg font-medium text-fg">{askHeading}</h2>
      {chattable ? (
        <>
          <p className="mt-1 text-sm text-fg-3">
            Answers cite the passages they are built from. Open a citation to read the source.
          </p>
          <NewChatComposer expert={expert} className="mt-3" />
        </>
      ) : (
        <Notice tone="info" className="mt-3">
          This expert cannot answer yet — nothing has been read from its sources.{' '}
          {building && buildStatus ? (
            <>
              <Link
                href={`/experts/${expert.name}/build`}
                className="text-fg underline underline-offset-2"
              >
                Watch the build
              </Link>
              .
            </>
          ) : owner ? (
            <>
              <Link
                href={`/experts/${expert.name}/settings`}
                className="text-fg underline underline-offset-2"
              >
                Start a build
              </Link>
              .
            </>
          ) : (
            'Its owner has not built it yet.'
          )}
        </Notice>
      )}

      {/* `lg:hidden`, as Home's own recents are: from `lg` the sidebar lists
          this expert's chats twenty pixels to the left, and two lists of the
          same six things choosing different secondary facts is worse than one.
          Below `lg` there is no sidebar, so this is the only route to them —
          and it carries the same relative time the sidebar does. */}
      {conversations.length > 0 && (
        <ul className="mt-4 space-y-0.5 rounded-card bg-panel p-1 lg:hidden">
          {conversations.slice(0, 6).map((conversation) => (
            <li key={conversation.id}>
              <Link
                href={`/chats/${conversation.id}`}
                className="flex h-(--row-h) items-center gap-2 rounded-row px-2 text-sm transition-colors duration-(--dur-1) hover:bg-raised"
              >
                <span className="min-w-0 flex-1 truncate text-fg-2">
                  {chatTitle(conversation.title)}
                </span>
                <RelativeTime
                  iso={conversation.last_message_at}
                  className="shrink-0 text-xs text-fg-3"
                />
              </Link>
            </li>
          ))}
          {conversations.length > 6 && (
            <li>
              <Link
                href="/chats"
                className="flex h-(--row-h) items-center rounded-row px-2 text-sm text-fg-3 transition-colors duration-(--dur-1) hover:bg-raised hover:text-fg-2"
              >
                See all {plural(conversations.length, 'chat')}
              </Link>
            </li>
          )}
        </ul>
      )}
    </section>
  )

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <TopBar
        expert={expert}
        // The crumb before it is already the expert's name; repeating it as
        // the leaf read "Thomism / Thomism". Every other expert page names
        // itself here, so this one does too.
        title="Overview"
        action={
          chattable ? (
            /**
             * Quiet, and it puts the cursor where it says it will: a filled
             * pill here outshouted a page whose own content is the point.
             */
            <Button
              variant="secondary"
              size="action"
              aria-label={askHeading}
              onClick={() => {
                const field = document.getElementById(ASK_FIELD_ID)
                const still = window.matchMedia('(prefers-reduced-motion: reduce)').matches
                document
                  .getElementById('ask')
                  ?.scrollIntoView({ behavior: still ? 'auto' : 'smooth', block: 'start' })
                // `preventScroll`, or focusing fights the smooth scroll it was
                // meant to finish.
                field?.focus({ preventScroll: true })
              }}
              className="shrink-0"
            >
              <MessageSquare className="size-3.5" />
              <span className="hidden sm:inline">Ask</span>
            </Button>
          ) : building ? (
            <ButtonLink
              variant="outline"
              size="md"
              href={`/experts/${expert.name}/build`}
              className="shrink-0"
            >
              Building…
            </ButtonLink>
          ) : undefined
        }
        overflow={
          <>
            {/* Share first: from `lg` the rows under it are all in the sidebar
                beside this menu, and sharing is the one thing that lives only
                here — it was last. */}
            {owner && <MenuItem onClick={() => setSharing(true)}>Share…</MenuItem>}
            <MenuLinkItem render={<Link href={`/experts/${expert.name}/sources`} />}>
              Sources
            </MenuLinkItem>
            <MenuLinkItem render={<Link href={`/experts/${expert.name}/graph`} />}>
              Concepts
            </MenuLinkItem>
            {owner ? (
              <MenuLinkItem render={<Link href={`/experts/${expert.name}/settings`} />}>
                Expert settings
              </MenuLinkItem>
            ) : (
              <>
                <MenuSeparator />
                <MenuItem onClick={() => void leave()}>Remove from my experts</MenuItem>
              </>
            )}
          </>
        }
      />

      <div className="scroll-col relative flex-1">
        <div className="mx-auto w-full max-w-[720px] px-4 pt-5 pb-16 md:px-6">
          {/* Failed and degraded notices sit above the properties, where the
              first question ("why is this not working") is answered first. */}
          {expert.status === 'failed' && (
            <FailureNotice
              slug={expert.name}
              raw={expert.error ?? buildStatus?.last_error ?? null}
              answerable={chattable}
              canRebuild={owner}
            />
          )}

          {degradedPersona && (
            <Notice tone="warn" title="No voice was written for this expert" className="mb-5">
              It answers from its sources as normal.
              {owner && ' Rebuilding writes a name, a bio and a voice for it.'}
            </Notice>
          )}

          {chattable && expert.readiness === 'chat_ready' && building && (
            <Notice tone="info" title="It can answer now" className="mb-5">
              Answers already cite its sources. When the concept map finishes, they will also draw
              on related concepts and flag where sources disagree.
            </Notice>
          )}

          <OverviewHeader expert={expert} owner={owner} />

          {askFirst && ask}

          <OverviewProperties expert={expert} buildStatus={buildStatus} failed={failed} />

          {!failed && (
            <>
              <OverviewCoverage expert={expert} />

              {!askFirst && ask}
            </>
          )}
        </div>
      </div>

      {owner && (
        <ShareDialog slug={expert.name} name={name} open={sharing} onOpenChange={setSharing} />
      )}
    </div>
  )
}

function FailureNotice({
  slug,
  raw,
  answerable,
  canRebuild,
}: {
  slug: string
  raw: string | null
  answerable: boolean
  canRebuild: boolean
}) {
  const { headline, advice } = describeBuildFailure(raw)
  return (
    <Notice
      tone="bad"
      title="This build failed"
      className="mb-5"
      action={
        canRebuild ? (
          <ButtonLink variant="outline" size="sm" href={`/experts/${slug}/settings`}>
            <RotateCcw className="size-3" />
            Rebuild
          </ButtonLink>
        ) : undefined
      }
    >
      <p>
        {headline} {answerable ? 'It still answers from the sources it already had. ' : ''}
        {advice}
      </p>
      {raw && (
        <details className="mt-1.5 text-xs text-fg-3">
          <summary className="cursor-pointer">Technical detail</summary>
          <p className="mt-1 font-mono break-words">{raw}</p>
        </details>
      )}
    </Notice>
  )
}

/** Source counts by kind, largest first, merging fetchers that share a kind. */
