'use client'

import { MessageSquare, RotateCcw } from 'lucide-react'
import Link from 'next/link'
import { ViewTransition } from 'react'

import { Avatar } from '@/components/identity/avatar'
import { AvatarPicker } from '@/components/identity/avatar-picker'
import { PictureCredit } from '@/components/identity/picture-credit'
import { ASK_FIELD_ID, NewChatComposer } from '@/components/chat/new-chat-composer'
import { TopBar } from '@/components/shell/top-bar'
import { DateText } from '@/components/ui/relative-time'
import { Button, ButtonLink } from '@/components/ui/button'
import { MenuLinkItem } from '@/components/ui/menu'
import { Notice } from '@/components/ui/notice'
import { StatusDot, dotState, stateLabel, statusTextClass } from '@/components/ui/status-dot'
import { describeBuildFailure } from '@/lib/build/copy'
import { cn } from '@/lib/cn'
import {
  chatTitle,
  firstSentence,
  formatPercent,
  formatScore,
  humanise,
  plural,
} from '@/lib/format'
import { displayName, subtitle } from '@/lib/persona'
import { sourceKind } from '@/lib/source-kind'
import type {
  BuildStatus,
  ConversationSummary,
  CorpusReport,
  ExpertWithCatalog,
} from '@/lib/api/types'

/**
 * The expert's Overview: a document, not a dashboard.
 *
 * Sigil where the reference has its emoji, the persona name as a 24px title,
 * the topic as the description line, then a properties block of inline
 * label · value rows, then prose sections. The properties stack label-over-value
 * below 480px rather than squeezing two columns into 360px.
 *
 * **Asking comes first for a new expert.** With no chats yet, the composer sits
 * directly under the header: the payoff of a build is asking it something, and
 * as the last section of a long document it was the thing people had to go and
 * find. Once there are chats it returns to the foot of the page, beside them.
 *
 * **A failed build shows the failure and nothing that describes a corpus.** A
 * failed expert has no sources to have assembled, so the notice, the properties
 * and the way back are the whole page.
 *
 * **Chat is gated on `readiness`, never on `status`.** An expert whose chunks
 * are embedded answers questions a whole stage before its build job finishes,
 * and reading `status` here would hide a working expert for the length of graph
 * extraction.
 */
export function OverviewPage({
  expert,
  conversations,
  buildStatus,
  report,
}: {
  expert: ExpertWithCatalog
  conversations: ConversationSummary[]
  buildStatus: BuildStatus | null
  report: CorpusReport | null
}) {
  const name = displayName(expert)
  const chattable = expert.readiness !== 'pending'
  const state = dotState(expert.status, expert.readiness, expert.build_active)
  const building = state === 'queued' || state === 'building'
  const failed = expert.status === 'failed' && !chattable
  const askFirst = chattable && conversations.length === 0
  // A build that finished but left no persona: the corpus is usable and the
  // voice can be regenerated by rebuilding. Worth saying, not worth hiding.
  const degradedPersona = expert.status === 'ready' && !expert.persona_name
  const voice = firstSentence(expert.persona_style)

  const statusText =
    state === 'ready' && expert.readiness === 'graph_ready'
      ? 'Ready · concept map built'
      : stateLabel(state)

  const ask = (
    <section id="ask" className={cn('scroll-mt-16', askFirst ? 'mt-6' : 'mt-10')}>
      <h2 className="text-lg font-medium text-fg">Ask {name}</h2>
      {chattable ? (
        <>
          <p className="mt-1 text-sm text-fg-3">
            Answers cite the passages they are built from. Open a citation to read the source.
          </p>
          <NewChatComposer expert={expert} className="mt-3" />
        </>
      ) : (
        <Notice tone="info" className="mt-3">
          This expert cannot answer yet — nothing has been read from its sources.{' '}
          {building && buildStatus ? (
            <Link
              href={`/experts/${expert.name}/build`}
              className="text-fg underline underline-offset-2"
            >
              Watch the build
            </Link>
          ) : (
            <Link
              href={`/experts/${expert.name}/settings`}
              className="text-fg underline underline-offset-2"
            >
              Start a build
            </Link>
          )}
          .
        </Notice>
      )}

      {conversations.length > 0 && (
        <ul className="mt-4 space-y-0.5 rounded-card bg-panel p-1">
          {conversations.slice(0, 6).map((conversation) => (
            <li key={conversation.id}>
              <Link
                href={`/chats/${conversation.id}`}
                className="flex h-(--row-h) items-center gap-2 rounded-row px-2 text-sm transition-colors duration-(--dur-1) hover:bg-raised"
              >
                <span className="min-w-0 flex-1 truncate text-fg-2">
                  {chatTitle(conversation.title)}
                </span>
                <span className="shrink-0 text-xs text-fg-3">
                  {plural(conversation.message_count, 'message')}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </section>
  )

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <TopBar
        expert={expert}
        // The crumb before it is already the expert's name; repeating it as
        // the leaf read "Thomism / Thomism". Every other expert page names
        // itself here, so this one does too.
        title="Overview"
        action={
          chattable ? (
            /**
             * Quiet, and it puts the cursor where it says it will: a filled
             * pill here outshouted a page whose own content is the point.
             */
            <Button
              variant="secondary"
              size="action"
              aria-label={`Ask ${name}`}
              onClick={() => {
                const field = document.getElementById(ASK_FIELD_ID)
                const still = window.matchMedia('(prefers-reduced-motion: reduce)').matches
                document
                  .getElementById('ask')
                  ?.scrollIntoView({ behavior: still ? 'auto' : 'smooth', block: 'start' })
                // `preventScroll`, or focusing fights the smooth scroll it was
                // meant to finish.
                field?.focus({ preventScroll: true })
              }}
              className="shrink-0"
            >
              <MessageSquare className="size-3.5" />
              <span className="hidden sm:inline">Ask</span>
            </Button>
          ) : building ? (
            <ButtonLink
              variant="outline"
              size="md"
              href={`/experts/${expert.name}/build`}
              className="shrink-0"
            >
              Building…
            </ButtonLink>
          ) : undefined
        }
        overflow={
          <>
            <MenuLinkItem render={<Link href={`/experts/${expert.name}/sources`} />}>
              Sources
            </MenuLinkItem>
            <MenuLinkItem render={<Link href={`/experts/${expert.name}/graph`} />}>
              Graph
            </MenuLinkItem>
            <MenuLinkItem render={<Link href={`/experts/${expert.name}/settings`} />}>
              Settings
            </MenuLinkItem>
          </>
        }
      />

      <div className="scroll-col relative flex-1">
        <div className="mx-auto w-full max-w-[720px] px-4 pt-5 pb-16 md:px-6">
          {/* Failed and degraded notices sit above the properties, where the
              first question ("why is this not working") is answered first. */}
          {expert.status === 'failed' && (
            <FailureNotice
              slug={expert.name}
              raw={expert.error ?? buildStatus?.last_error ?? null}
              answerable={chattable}
            />
          )}

          {degradedPersona && (
            <Notice tone="warn" title="No voice was written for this expert" className="mb-5">
              It answers from its sources as normal. Rebuilding writes a name, a bio and a voice for
              it.
            </Notice>
          )}

          {chattable && expert.readiness === 'chat_ready' && building && (
            <Notice tone="info" title="It can answer now" className="mb-5">
              Answers already cite its sources. When the concept map finishes, they will also draw
              on related concepts and flag where sources disagree.
            </Notice>
          )}

          <header className="flex items-start gap-4">
            <ViewTransition name={`sigil-${expert.name}`}>
              <div>
                <AvatarPicker expert={expert}>
                  <Avatar expert={expert} size={48} />
                </AvatarPicker>
              </div>
            </ViewTransition>
            <div className="min-w-0 flex-1">
              <h1 className="text-title font-medium text-fg">{name}</h1>
              {subtitle(expert) && <p className="mt-1 text-sm text-fg-2">{subtitle(expert)}</p>}
              {voice && (
                // The first sentence of the voice, whole. The builder sometimes
                // writes a paragraph here, and clamping it cut a sentence off
                // mid-clause; the full text is on the title for anyone curious.
                <p
                  title={expert.persona_style ?? undefined}
                  className="mt-1 text-sm text-fg-3 italic"
                >
                  {voice}
                </p>
              )}
              {/* Only where the picture is actually what is shown: an owner who
                  pinned a drawing is not using the picture, and crediting it
                  under someone else's tile would be a claim about the wrong
                  image. `PictureCredit` itself drops out for public domain. */}
              {expert.picture && !expert.avatar && (
                <PictureCredit picture={expert.picture} className="mt-1.5" />
              )}
            </div>
          </header>

          {askFirst && ask}

          {/* Properties: label in --fg-3, value as text. Stacks below 480px so
              nothing truncates on a phone. */}
          <dl className="mt-6 grid grid-cols-1 gap-x-6 gap-y-2 text-sm min-[480px]:grid-cols-[auto_1fr]">
            <Property label="Status">
              {/* One line for what used to be two adjacent rows — "Status: Ready"
                  and "Readiness: Graph-ready — retrieval expands with concepts"
                  — which read as the same fact said twice. */}
              <span className="inline-flex items-center gap-1.5">
                <StatusDot state={state} />
                <span className={statusTextClass[state]}>{statusText}</span>
              </span>
            </Property>
            <Property label="Depth">
              <span className="text-fg-2">{humanise(expert.tier)}</span>
            </Property>
            {!failed && (
              <>
                <Property label="Sources">
                  {report ? (
                    <span className="text-fg-2">
                      {report.totals.accepted} kept of {report.totals.considered} screened
                    </span>
                  ) : (
                    <span className="text-fg-2">{expert.source_count}</span>
                  )}
                </Property>
                <Property label="Quality">
                  <span className="text-fg-2">{formatScore(expert.avg_quality)} average</span>
                  {report?.thresholds && (
                    <span className="ml-1.5 text-xs text-fg-3">
                      out of 10 · a source needs {report.thresholds.quality_min} for quality and{' '}
                      {report.thresholds.relevance_min} for relevance to be kept
                    </span>
                  )}
                </Property>
                <Property label="Passages">
                  <span className="text-fg-2">{expert.chunk_count}</span>
                </Property>
                {expert.node_count > 0 && (
                  <Property label="Concepts">
                    <span className="text-fg-2">
                      {plural(expert.node_count, 'concept')} · {plural(expert.edge_count, 'link')}
                    </span>
                  </Property>
                )}
              </>
            )}
            <Property label="Built">
              <DateText iso={expert.created_at} className="text-fg-2" />
            </Property>
          </dl>

          {!failed && (
            <>
              {expert.persona_bio && (
                <Section title="About">
                  <p>{expert.persona_bio}</p>
                </Section>
              )}

              {expert.key_concepts.length > 0 && (
                <Section title="Key concepts">
                  <p className="text-fg-3">
                    What the search set out to cover. Each one opens the sources that cover it.
                  </p>
                  <p className="mt-2 leading-relaxed">
                    {expert.key_concepts.map((concept, index) => (
                      <span key={concept}>
                        {index > 0 && <span className="text-fg-3"> · </span>}
                        <Link
                          href={`/experts/${expert.name}/sources?concept=${encodeURIComponent(concept)}`}
                          className="text-fg underline decoration-fg-4 underline-offset-2 hover:decoration-fg-2"
                        >
                          {concept}
                        </Link>
                      </span>
                    ))}
                  </p>
                </Section>
              )}

              {report && (
                <Section title="How these sources were chosen">
                  <p>{report.method_statement}</p>
                  <ul className="mt-3 space-y-1.5">
                    <li>
                      <span className="font-medium text-fg">Kept.</span> {report.totals.accepted} of{' '}
                      {report.totals.considered} sources screened (
                      {formatPercent(report.totals.acceptance_rate, 1)}). The{' '}
                      {report.totals.rejected} dropped are on the{' '}
                      <Link
                        href={`/experts/${expert.name}/sources?decision=rejected`}
                        className="text-fg underline underline-offset-2"
                      >
                        Sources page
                      </Link>{' '}
                      with the reason for each — they are the evidence that the rest were chosen.
                    </li>
                    <li>
                      <span className="font-medium text-fg">Screening rules.</span> A source scored
                      below {report.thresholds.quality_min} for quality or{' '}
                      {report.thresholds.relevance_min} for relevance is dropped, with the reason
                      recorded. Rules version{' '}
                      <span className="font-mono text-xs">
                        {report.thresholds.current_rubric_version}
                      </span>
                      .
                    </li>
                    {report.by_search.distinct_searches > 0 && (
                      <li>
                        <span className="font-medium text-fg">Searches.</span>{' '}
                        {plural(report.by_search.distinct_searches, 'search', 'searches')} found
                        these sources, including any follow-up searches for concepts that had no
                        source yet.
                      </li>
                    )}
                    {!report.provenance.complete && (
                      <li>
                        <span className="font-medium text-warn">Some records are incomplete.</span>{' '}
                        {report.provenance.note}
                      </li>
                    )}
                  </ul>
                </Section>
              )}

              {Object.keys(expert.source_type_counts).length > 0 && (
                <Section title="Kinds of source">
                  <p className="leading-relaxed">
                    {kindCounts(expert.source_type_counts).map(([kind, count], index) => (
                      <span key={kind}>
                        {index > 0 && <span className="text-fg-3"> · </span>}
                        <span className="text-fg-2">{kind}</span>{' '}
                        <span className="text-fg-3">{count}</span>
                      </span>
                    ))}
                  </p>
                </Section>
              )}

              {!askFirst && ask}
            </>
          )}
        </div>
      </div>
    </div>
  )
}

function FailureNotice({
  slug,
  raw,
  answerable,
}: {
  slug: string
  raw: string | null
  answerable: boolean
}) {
  const { headline, advice } = describeBuildFailure(raw)
  return (
    <Notice
      tone="bad"
      title="This build failed"
      className="mb-5"
      action={
        <ButtonLink variant="outline" size="sm" href={`/experts/${slug}/settings`}>
          <RotateCcw className="size-3" />
          Rebuild
        </ButtonLink>
      }
    >
      <p>
        {headline} {answerable ? 'It still answers from the sources it already had. ' : ''}
        {advice}
      </p>
      {raw && (
        <details className="mt-1.5 text-xs text-fg-3">
          <summary className="cursor-pointer">Technical detail</summary>
          <p className="mt-1 font-mono break-words">{raw}</p>
        </details>
      )}
    </Notice>
  )
}

/** Source counts by kind, largest first, merging fetchers that share a kind. */
function kindCounts(counts: Record<string, number>): [string, number][] {
  const merged = new Map<string, number>()
  for (const [type, count] of Object.entries(counts)) {
    const kind = sourceKind(type)
    merged.set(kind, (merged.get(kind) ?? 0) + count)
  }
  return [...merged.entries()].sort((a, b) => b[1] - a[1])
}

function Property({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="contents">
      <dt className="text-fg-3 min-[480px]:text-right">{label}</dt>
      <dd className="min-w-0">{children}</dd>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-medium text-fg">{title}</h2>
      <div className="mt-2 space-y-2 text-base leading-relaxed text-fg-2">{children}</div>
    </section>
  )
}
