"""Domain entities – pure Python, no framework dependencies."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ExpertStatus(str, Enum):
    PENDING = "pending"
    BUILDING = "building"
    READY = "ready"
    FAILED = "failed"


class Difficulty(str, Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    CUSTOM = "custom"


class SourceDocument(BaseModel):
    """A single ingested source document."""

    url: str
    title: str
    content: str
    source_type: str  # "web", "arxiv", "youtube", "crawl"
    metadata: dict = Field(default_factory=dict)


class Expert(BaseModel):
    """The Peritus expert entity for a given topic."""

    slug: str = Field(description="URL-safe unique identifier derived from topic")
    topic: str = Field(description="The original topic string")
    persona_name: str = Field(description="Human-readable expert name, e.g. 'Quantum Computing Expert'")
    description: str = Field(default="", description="Auto-generated description of what this expert knows")
    status: ExpertStatus = Field(default=ExpertStatus.PENDING)
    source_count: int = Field(default=0)
    node_count: int = Field(default=0)
    relation_count: int = Field(default=0)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    storage_path: str = Field(default="")
    pinecone_namespace: str = Field(default="")

    def mark_building(self) -> None:
        self.status = ExpertStatus.BUILDING

    def mark_ready(self, source_count: int, node_count: int, relation_count: int) -> None:
        self.status = ExpertStatus.READY
        self.source_count = source_count
        self.node_count = node_count
        self.relation_count = relation_count

    def mark_failed(self) -> None:
        self.status = ExpertStatus.FAILED


class CourseModule(BaseModel):
    """A single module (chapter) inside a course."""

    title: str
    summary: str
    key_concepts: list[str] = Field(default_factory=list)
    content: str = Field(description="Full markdown content for this module")
    citations: list[str] = Field(default_factory=list)


class Course(BaseModel):
    """A structured learning course generated by a Peritus expert."""

    expert_slug: str
    title: str
    difficulty: Difficulty
    focus: Optional[str] = None
    introduction: str
    modules: list[CourseModule] = Field(default_factory=list)
    conclusion: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class ChatMessage(BaseModel):
    """A single message in a chat conversation."""

    role: str  # "user" | "assistant"
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Conversation(BaseModel):
    """An ongoing conversation with a Peritus expert."""

    expert_slug: str
    messages: list[ChatMessage] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=datetime.utcnow)

    def add_message(self, role: str, content: str) -> ChatMessage:
        msg = ChatMessage(role=role, content=content)
        self.messages.append(msg)
        return msg
